### ISSUE TITLE
Nav highlighting for sections

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#13] opened 2021-01-20 20:31 UTC
This is… a tricky problem because of how your URLs are laid out, in that you can't detect a "section" of the site from the URL alone.  There's no real problem with a "flat" structure to your site, except that if I click to the bibliography page, the nav has a highlight under "home" that makes me feel like I'm not in the "misc" section, which is in fact how I got to the bibliography.  That kind of thing is confusing to the user, so I would recommend either removing the highlight under home or ideally working out a system to indicate which section you're on in the nav.  If that's something you're interested in, I would definitely wait until a site restructure / tech change because it will be easier to set up with a static site generator or web framework than it would be with javascript, but certainly javascript to parse the URL and then apply a class to a nav section would work, too.

**Comment by awisnicki** [comment] 2021-02-06 13:36
There's a two part answer to this. For now, I've removed the underline from home (and the links in the dropdowns), and the underline now only appears when one hovers over a link either in the top menu or in the dropdowns (same as what UNL does on its pages incidentally :> )

That said, I take your point that it would help users to know what section they were in by the corresponding linking being highlighted in the top menu/nav. 

Based on comments you've made in other issues, I've planning to redo the nav as it is and, as you know, will also work on converting the site to a static site generator. Somewhere in that process, I'll also plan on sorting out the issue of the user's current section being highlighted. 

For now, I'll go ahead and close this issue.

**Closed as completed by awisnicki** 2021-02-06 13:36 UTC
Labels: somewhat complicated

**Comment by awisnicki** [comment] 2021-02-08 17:33
> but certainly javascript to parse the URL and then apply a class to a nav section would work, too.

@jduss4 I'm working on #12 at present, but it occurred to me that I have a question related to this point that you make in this issue. As noted, I have a flat site and that's in part due to the fact that I'm reluctant to group pages into directories/sections as I may eventually come up with a different organization scheme, but as a result the URL for any given page doesn't have any info other than main site URL plus the file name of the page itself. As a result, I'm not sure I understand how you imagine the point you make about parsing working in the context I describe. Can you elaborate a little bit more? Do you have an example you could give me of how this works? I get it conceptually and could work it out practically, but the key issue is that I don't see what I'd be grabbing as the URL doesn't have an intervening subdirectory name.

**Comment by jduss4** [comment] 2021-02-08 18:04
@awisnicki Yes, that would be a problem with a flat site structure, unfortunately.

As it is now, you would have to hardcode something to recognize patterns.  In pseudo code something like:

```
if "about" or "/"
  "home"
elsif starts with "periodical" or contains "tei."
  "newspapers"
```
etc.

One nice thing about a static site generator, if you are ultimately putting things in there, is that most of them will let you set variables on your pages somewhere so that you can set the navigation based on that.  Also in pseudo code:

```
# new page
---
title: Cool New Page
section: newspapers
---
```

```
# navigation.html
<a href="home" class="<% 'active' if section == "home" %>">Home</a>
<a href="news" class="<% 'active' if section == "newspapers" %>">Newspapers</a>
```

**Comment by awisnicki** [comment] 2021-02-09 15:09
@jduss4 I'm working on the nav now, pre-migration to a static site generator, so if I can use a variant of your "pseudo code" now I'll give it a try; if not, then I'll definitely tackle this when I come to the static site generator. Thanks again!

**Comment by awisnicki** [comment] 2021-02-13 22:27
For the record, I was able to sort this out. Here's the code:

```
    checkUrl();
    
    function checkUrl () {
        if(location.pathname == "/" && 
            location.hash.length <= 1 && 
            location.search.length <= 1) {
                document.getElementById("home-tab").setAttribute("class","current");
        }
        if (window.location.href.indexOf("index") > -1) {	
                document.getElementById("home-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("texts") > -1 ||
            window.location.href.indexOf("objects") > -1 ||
            window.location.href.indexOf("books") > -1 ||
            window.location.href.indexOf("motion") > -1 ||
            window.location.href.indexOf("essays") > -1 ||
            window.location.href.indexOf("_TEI") > -1 ||
            window.location.href.indexOf("_ART") > -1) {	
                document.getElementById("materials-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("analytical") > -1 ||
            window.location.href.indexOf("design") > -1 ||
            window.location.href.indexOf("collaboration") > -1 ||
            window.location.href.indexOf("guidelines") > -1) {	
                document.getElementById("concepts-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("contributors") > -1 ||
            window.location.href.indexOf("acknowledgments") > -1 ||
            window.location.href.indexOf("bibliography") > -1 ||
            window.location.href.indexOf("site_map") > -1) {	
                document.getElementById("misc-tab").setAttribute("class","current");
        };
    };
```

Ain't pretty, but it does the trick. If you have a suggestion for how to compress the repetitive bit of code (window.location.href.indexOf.....), please let me know. I haven't yet test this for when one is on root, but otherwise works well!

**Comment by awisnicki** [comment] 2021-02-14 01:05
Follow up: Now also tested and confirmed on root.
